name: Backup Firestore

on:
  schedule:
    - cron: "0 0 * * *"

env:
  PROJECT_ID: deckdeckgo-studio-prod
  BUCKET: gs://deckdeckgo-studio-backup

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.FIRESTORE_BACKUP_TOKEN }}
          export_default_credentials: true
        if: github.repository == 'deckgo/deckdeckgo'
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
